### PR TITLE
favicon for safari

### LINKED ISSUE #185: Favicon is not shown on Safari
Favicon is not shown on Safari, while it's shown on Chrome.
It didnt fix even after deleting cache.

### PR DESCRIPTION
**Pull request by Gumichocopengin8**
- close #185
- Favicon is not shown on Safari, so support it!

### CODE REVIEW

**Comment by Gumichocopengin8** [comment]
@lucacasonato Hello, could you review this PR for me? Thanks!

**Comment by kt3k** [comment]
@Gumichocopengin8 Thanks for the contribution! This fixes the issue in safari, but now chrome doesn't use svg with this change. Maybe the tag for svg icon should be the first? And do we need to add .png icon when we already have .ico icon?

**Comment by Gumichocopengin8** [comment]
@kt3k Thanks for reviewing. I agree to change the order of favicon extensions. 
PNG is for smartphone, but I forgot to add `apple-touch-icon` as rel.
Do you agree with it?

**Comment by kt3k** [comment]
@Gumichocopengin8 Thanks for updating! I confirmed this works in localhost, but very strangely this doesn't work in vercel preview (Chrome chooses .ico icon instead of svg icon) (See https://doc-website-ampwefmvu-denoland.vercel.app/ in dark mode if possible)

After having searched a little, I found this Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=1162276
It says chromium now has a bug in choosing favicon between .svg and .ico. The workaround here looked like adding `sizes` attribute lowers the priority of the favicon. So could you try add `sizes="16x16"` attr to the tag of `.ico` icon?

**Comment by Gumichocopengin8** [comment]
@kt3k Thanks. I didnt notice that. I used 32x32 instead of 16x16 cuz 32x32 is the standard size.

**Comment by Gumichocopengin8** [comment]
Now favicon is not shown in safari...

**Comment by Gumichocopengin8** [comment]
@kt3k Everything works now. I made a stupid mistake in this PR. Do you think it's a good idea to make a new PR for this cuz this PR is now messy?

**Review by kt3k — APPROVED** [review]
@Gumichocopengin8 Thanks for the updates. Now everything looks working! LGTM

No need of another PR because we use 'squash merge'. This PR will become a single commit.

**Pull request merged**
