### PR TITLE
Added ids to headers for scroll anchoring

### PR DESCRIPTION
**Pull request by lucacasonato**

### CODE REVIEW

**Comment by lucacasonato** [comment]
The issue with deploying is back. I'll reach out to ZEIT support again.

**Comment by paulogdm** [comment]
Checking with the team. We will get back to you.

**Comment by paulogdm** [comment]
We are having an issue with your builds in the upstream provider. Once I have news, I will share them here.

**Comment by paulogdm** [comment]
We've located a regression and we are working with AWS to fix it as soon as possible.
My sincere apologies everyone. The team is on top of it as we speak.

**Comment by paulogdm** [comment]
@lucacasonato We've fixed this issue for the "deno" team. My apologies for the disruption.

**Comment by lucacasonato** [comment]
@paulogdm Thanks for the help 👍

**Comment by ry** [comment]
Oops please merge with master (or did this stuff get landed in your other PR?)

**Comment by lucacasonato** [comment]
> Oops please merge with master (or did this stuff get landed in your other PR?)

It did not get merged already. Merged with master.

**Pull request merged**
